[package]
name = "snarkvm-debugdata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.indexmap]
version = "1.8.0"
features = [ "serde-1" ]


[dependencies.serde]
version = "1.0"


[dependencies]
